name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet CLI
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Android NDK (27.0.12077973)
        run: |
          # قبول التراخيص باستخدام المسار الصحيح والمباشر لـ sdkmanager في جيت هوب
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          # تثبيت إصدار الـ NDK المطلوب لـ Gradle لتجنب خطأ التفضيل
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;27.0.12077973"

      - name: Build APK using Flet
        run: python -m flet build apk --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasiba-app-apk
          path: build/apk/*.apk
